### ISSUE TITLE
服务不可用

### ISSUE THREAD

**Issue by bowling233** [zmh-program/bilibili-stats#1]
如下图所示，输入任何 UID 均显示访问的 UID 不存在。
![image](https://github.com/zmh-program/bilibili-stats/assets/35755846/1576cb23-96ae-4467-b591-e0975c63a95c)
希望能修复或在 README 中指导一下如何自行部署🥺🥺🥺

**Comment by zmh-program** [comment]
嘶，看样子是B站API又又又更换了，逆向不成功。如果何事有空我会尝试再修复。

部署的话package.json都有了，直接按照正常流程走就行 npm run start即可

**Comment by bowling233** [comment]
好的，感谢🤗
